### ISSUE TITLE
.sb2

### ISSUE THREAD

**Issue by bjskistad** [chewiesoft/chewieos#2]
It isn't a great idea to write the whole OS in .sb2 file format. It's not a good idea to have any file written in .sb2! .sb2 is only interpreted by Scratch's Flash Player.

**Comment by Darpion** [comment]
The whole point of this OS is to create the best possible OS to run in Scratch. If we made it run in say, C or C++, the point would be ruined.

**Comment by bjskistad** [comment]
Ahh... I thought you were making an actual OS.

**Comment by Darpion** [comment]
nonono XD
